site_name: Shixiang's Mark List
docs_dir: "docs"
site_dir: "site"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
repo_url: https://github.com/ShixiangWang/MarkList
edit_uri: https://github.com/ShixiangWang/MarkList/edit/main/
site_author: Shixiang Wang
copyright: Copyright © 2021 ShixiangWang
nav:
    - Home: README.md
    - About: https://shixiangwang.github.io/
markdown_extensions:
    - smarty
    - toc:
        permalink: True
        separator: "-"
        toc_depth: 4

